# Generated by Django 6.0.3 on 2026-04-01 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='developers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'DEV'}, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
